#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "remove" ] && [ -x "/etc/init.d/irqbalance" ] ; then
	chmod -x "/etc/init.d/irqbalance" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d irqbalance remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/init/irqbalance.conf 1.2.0-0.1\~ -- "$@"
# End automatically added section
# Automatically added by dh_runit/2.15.2
# Unfortunately, we can not assume, that bin:runit-helper package
# is installed at postrm stage.
#
# The only other option is embed whole runit-helper script here,
# into postrm script of -run package, but it would be like static
# linking, requiring rebuild of all reverse dependencies on every
# change of dh-runit.
if [ -z "${DPKG_ROOT:-}" ] && [ -x /lib/runit-helper/runit-helper ] ; then
   NAME='irqbalance' ENABLE='yes' ONUPGRADE='restart' /lib/runit-helper/runit-helper postrm "$@"
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'irqbalance.service' >/dev/null || true
	fi
fi
# End automatically added section
