#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/init/irqbalance.conf 1.2.0-0.1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/irqbalance" ] ; then
	chmod +x "/etc/init.d/irqbalance" >/dev/null || true
fi
# End automatically added section
