#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'irqbalance.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/irqbalance" ] ; then
	invoke-rc.d --skip-systemd-native irqbalance stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/init/irqbalance.conf 1.2.0-0.1\~ -- "$@"
# End automatically added section
# Automatically added by dh_runit/2.15.2
# Unlike postrm, I can be sure, that runit-helper is present on
# prerm.
if [ -z "${DPKG_ROOT:-}" ] ; then
    NAME='irqbalance' ENABLE='yes' ONUPGRADE='restart' /lib/runit-helper/runit-helper prerm "$@"
fi
# End automatically added section
